import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const Aeonik = localFont({ 
  src: './fonts/_Aeonik-Regular.otf',
  variable: '--font-aeonik',
});

const BickhamScript = localFont({ 
  src: './fonts/_Bickham Script Pro Regular.ttf',
  variable: '--font-bickham',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Aeonik.variable} ${BickhamScript.variable}`}>
        {children}
      </body>
    </html>
  );
}
