import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { fontAeonik, fontBickhamScript } from "@/assets/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cn('antialiased', fontAeonik.variable)} ${cn('antialiased', fontBickhamScript.variable)}`}>
        {children}
      </body>
    </html>
  );
}
